services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
     - '/ollama:~/.ollama'
    ports:
    # Port to expose on the machine : port to expose in the container
     - 11434:11434
