# Docker-compose help comes from: ai/chat-demo:latest

services:
  api-server:
    container_name: middleware-api-server
    build: "./Flask-backend/"
    restart: always
    ports:
      - "45689:45689"
    networks:
      backend:
        ipv4_address: 10.0.60.3
      database:
        ipv4_address: 10.0.61.3

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
     - '/ollama:/ollama'  # You might need to remove the ./ and replace it with you home directory (Docker doesn't like this)
    # Port to expose on the machine : port to expose in the container
    ports:
     - 11434:11434
    # If we need to limit the AI model, we can use this
    deploy:
      resources:
        limits:
          cpus: '4'   # Preferrably 4 for lightweight models, 16 for heavy models
          memory: 8G
        reservations:
          cpus: '0.25'
          memory: 2G  # Lightweight models require 2GB's of memory
    restart: always
    networks:
      backend:
        ipv4_address: 10.0.60.2

  # database-server:
  #   container_name: mysql-database
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: veryverysecretpassword
  #     MYSQL_DATABASE: nao6-db
  #     MYSQL_USER: username
  #     MYSQL_PASSWORD: themostsecretpassword
  #   ports:
  #   - "3306:3306"
  #   volumes:
  #   - db_data:/var/lib/mysql
  #   restart: always
  #   networks:
  #     database:
  #       ipv4_address: 10.0.61.2

volumes:
  ollama_data:
    name: ollama_data
  # db_data:
  #   name: mysql_data

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.60.0/28"
  # database:
  #   driver: bridge
  #   ipam:
  #     config: 
  #       - subnet: "10.0.61.0/28"
